import { EITHER_OR_ALLOWED_RESOLVE_AT, EITHER_OR_DEFAULT_RESOLVE_AT, STAT_KEY_LABELS as EITHER_OR_STAT_KEY_LABELS, STAT_KEY_TO_CATEGORY as EITHER_OR_STAT_KEY_TO_CATEGORY } from '../eitherOr/constants';

export const PROP_HUNT_ALLOWED_RESOLVE_AT = [...EITHER_OR_ALLOWED_RESOLVE_AT];
export const PROP_HUNT_DEFAULT_RESOLVE_AT = EITHER_OR_DEFAULT_RESOLVE_AT;

export const STAT_KEY_TO_CATEGORY = { ...EITHER_OR_STAT_KEY_TO_CATEGORY };
export const STAT_KEY_LABELS = { ...EITHER_OR_STAT_KEY_LABELS };

export const PROP_HUNT_LINE_RANGE = {
  min: 0.5,
  max: 499.5,
  step: 1,
  unit: 'points',
};

export const PROP_HUNT_DEBUG_FLAG = 'DEBUG_PROP_HUNT';
