import {
  STAT_KEY_TO_CATEGORY as SHARED_STAT_KEY_TO_CATEGORY,
  STAT_KEY_LABELS as SHARED_STAT_KEY_LABELS,
  ALLOWED_RESOLVE_AT,
  DEFAULT_RESOLVE_AT,
  getStatRange,
  DEFAULT_STAT_RANGE,
} from '../../utils/statConstants';

export const PROP_HUNT_ALLOWED_RESOLVE_AT = [...ALLOWED_RESOLVE_AT];
export const PROP_HUNT_DEFAULT_RESOLVE_AT = DEFAULT_RESOLVE_AT;

export const STAT_KEY_TO_CATEGORY = SHARED_STAT_KEY_TO_CATEGORY;
export const STAT_KEY_LABELS = SHARED_STAT_KEY_LABELS;

export const PROP_HUNT_LINE_RANGE = DEFAULT_STAT_RANGE;

export { getStatRange };

export const PROP_HUNT_DEBUG_FLAG = 'DEBUG_PROP_HUNT';
