import type { Request, Response, NextFunction } from 'express';
import { randomUUID } from 'crypto';

/**
 * Header name for the request ID.
 * Can be passed by client or generated by server.
 */
export const REQUEST_ID_HEADER = 'x-request-id';

/**
 * Key used to store request ID on the request object.
 */
export const REQUEST_ID_KEY = 'requestId';

/**
 * Extends Express Request type to include requestId.
 */
declare global {
  namespace Express {
    interface Request {
      requestId: string;
    }
  }
}

/**
 * Middleware that adds a unique request ID to each request.
 *
 * The request ID is:
 * 1. Taken from the incoming `X-Request-ID` header if present
 * 2. Otherwise generated as a new UUID
 *
 * The ID is:
 * - Stored on `req.requestId` for use in handlers and logging
 * - Added to the response as `X-Request-ID` header
 *
 * This enables request tracing across services and in logs.
 *
 * @example
 * // In index.ts
 * app.use(requestIdMiddleware);
 *
 * // In a controller
 * console.log(`[${req.requestId}] Processing request...`);
 *
 * // In logs, correlate by request ID
 * // [abc123] Processing request...
 * // [abc123] Database query completed
 * // [abc123] Response sent
 */
export function requestIdMiddleware(
  req: Request,
  res: Response,
  next: NextFunction,
): void {
  // Check for existing request ID from client/upstream service
  const existingId = req.headers[REQUEST_ID_HEADER];
  const requestId =
    typeof existingId === 'string' && existingId.length > 0
      ? existingId
      : randomUUID();

  // Attach to request for use in handlers
  req.requestId = requestId;

  // Add to response headers for client correlation
  res.setHeader(REQUEST_ID_HEADER, requestId);

  next();
}

/**
 * Creates a logger prefix with the request ID.
 * Useful for prefixing log messages with request context.
 *
 * @param req - Express request with requestId
 * @returns Formatted prefix string like "[abc123]"
 */
export function getRequestLogPrefix(req: Request): string {
  return `[${req.requestId}]`;
}
